cod1, qtd1, preco1 = input().split()
cod2, qtd2, preco2 = input().split()
cod1 = int(cod1)
qtd1 = int(qtd1)
preco1 = float(preco1)
cod2 = int(cod2)
qtd2 = int(qtd2)
preco2 = float(preco2)
valor = (qtd1*preco1)+(qtd2*preco2)
print ('VALOR A PAGAR: R$ {:.2f}'.format(valor))
